openapi: 3.0.0
info:
  title: Minitube API
  version: 2.0.0
  contact:
    name: Kevin Del Castillo Ramirez
    email: quebin31@gmail.com
paths:
  "/createVideo":
    description: |
      Operations related to video creation.
    get:
      summary: Create a new video.
      description: |
        Generates and returns a new video id and a presigned URL to put the video on
        the corresponding S3 bucket. In order to upload the video using the presigned URL 
        you must sent a request with the following contents:

        - Raw video data (binary) must be included in the request body.
        - HTTP method must be `PUT`.
        - Header `X-Amz-ACL` must be `public-read`.
        - Header `Content-Type` must be `video/mp4`, therefore only mp4 videos are accepted.
      operationId: createVideo
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateVideoResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  "/generateThumbnail":
    description: |
      Operations related to thumbnail configuration.
    post:
      summary: Generate video thumbnail.
      description: |
        Request thumbnail generation for the specified video id and the given
        video timestamp in seconds, this will save the generated thumbnail in 
        the corresponding S3 bucket.
      operationId: generateThumbnail
      requestBody:
        description: Video id and timestamp.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GenerateThumbnailRequest"
      responses:
        "200":
          description: Successful operation.
        "400":
          $ref: "#/components/responses/BadRequestError"
        "500":
          $ref: "#/components/responses/InternalError"

  "/detectAndSaveLabels":
    description: |
      Operations related to labels detection and save.
    post:
      summary: Detect and save video labels.
      description: |
        Request label detection for the specified video id, this will detect 
        labels for the previously generated thumbnail, save them on DynamoDB 
        and return them.
      operationId: detectAndSaveLabels
      requestBody:
        description: Video id.
        required: true
        content:
          application/json:
            schema:
              properties:
                video_id:
                  description: Video id.
                  type: string
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetectAndSaveLabelsResponse"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "500":
          $ref: "#/components/responses/InternalError"

  "/search":
    description: |
      Operations related to labels search.
    get:
      summary: Search videos with maching labels.
      description: |
        Search videos with matching labels specified in the query parameter, 
        these are internally transformed to lower case.
      operationId: search
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: Query string with space separated labels.
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResultResponse"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  schemas:
    CreateVideoResponse:
      properties:
        video_id:
          description: Generated video id.
          type: string
        presigned_url:
          description: Generated presigned URL (valid for 10 minutes).
          type: string
          format: uri

    GenerateThumbnailRequest:
      properties:
        video_id:
          description: Video id.
          type: string
        timestamp:
          description: The timestamp where the thumbnail will be generated.
          type: number
          format: seconds

    DetectAndSaveLabelsResponse:
      properties:
        labels:
          description: Thumbnail labels.
          type: array
          items:
            type: string

    SearchResultResponse:
      properties:
        videos:
          description: All the videos with matching labels.
          type: array
          items:
            description: Video information.
            type: object
            properties:
              labels:
                description: Matching labels.
                type: array
                items:
                  type: string
                minItems: 1
              thumbnail_url:
                description: URL to get thumbnail.
                type: string
                format: uri
              preview_url:
                description: URL to get preview.
                type: string
                format: uri
              video_url:
                description: URL to get video.
                type: string
                format: uri

    ErrorResponse:
      properties:
        error_type:
          description: Error type.
          type: string
          enum:
            - internal_error
            - bad_request
            - invalid_route
        info:
          description: More information on what failed.
          type: string

  responses:
    InternalError:
      description: There was an internal server error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    BadRequestError:
      description: Received an invalid request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
