openapi: 3.0.0
info:
  title: Minitube API
  version: 1.0.0
  contact:
    name: Kevin Del Castillo Ramirez
    email: quebin31@gmail.com
paths:
  "/requestUpload":
    description: |
      Operations related to video upload.
    get:
      summary: Request a presigned URL and video id.
      description: |
        Generates and returns a new video id and presigned URL to put the video on
        the corresponding S3 bucket.
      operationId: requestUpload
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestUpload"
        "500":
          $ref: "#/components/responses/InternalServerError"
  "/genThumbnails":
    description: |
      Operations related to thumbnail generation.
    get:
      summary: Start thumbnail generation.
      description: |
        Requests thumbnail generation for this video.
      operationId: genThumbnails
      parameters:
        - in: query
          name: video_id
          schema:
            type: string
          description: The video id for which thumbnails will be generated.
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenThumbnails"
        "400":
          $ref: "#/components/responses/InvalidRequestError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  "/uploadThumbnail":
    description: |
      Operations related to thumbnail selection.
    post:
      summary: Upload thumbnail for video.
      description: |
        Upload a thumbnail for the specified video id.
      operationId: uploadThumbnail
      requestBody:
        description: Video id and thumbnail data.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadThumbnail"
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadThumbnailResult"
        "400":
          $ref: "#/components/responses/InvalidRequestError"
        "500":
          $ref: "#/components/responses/InternalServerError"

  "/search":
    description: |
      Operations related to labels search.
    get:
      summary: Search videos with maching labels.
      description: |
        Search all the videos with the given labels.
      operationId: search
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Query string with space separated labels.
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
        "400":
          $ref: "#/components/responses/InvalidRequestError"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    RequestUpload:
      properties:
        video_id:
          description: Generated video id.
          type: string
        presigned_url:
          description: Generated presigned URL (valid for 10 minutes).
          type: string
          format: uri

    GenThumbnails:
      properties:
        data:
          description: Generated thumbnails data (`base64` encoded).
          type: array
          items:
            type: string
            format: base64
          minItems: 5
          maxItems: 5

    UploadThumbnail:
      properties:
        video_id:
          description: Selected video id.
          type: string
        thumbnail_data:
          description: Thumbnail data encoded in `base64`
          type: string
          format: base64

    UploadThumbnailResult:
      properties:
        video_id:
          description: Selected video id.
          type: string
        labels:
          description: Thumbnail labels.
          type: array
          items:
            type: string

    SearchResult:
      properties:
        videos:
          description: All the videos with matching labels.
          type: array
          items:
            description: Video information.
            type: object
            properties:
              labels:
                description: Matching labels.
                type: array
                items:
                  type: string
                minItems: 1
              thumbnail_url:
                description: URL to get thumbnail.
                type: string
                format: uri
              preview_url:
                description: URL to get preview.
                type: string
                format: uri
              video_url:
                description: URL to get video.
                type: string
                format: uri

    Error:
      properties:
        error_type:
          description: Error type.
          type: string
        info:
          description: More information on what failed.
          type: string

  responses:
    InternalServerError:
      description: There was an internal server error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    InvalidRequestError:
      description: Received an invalid request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
